### ISSUE TITLE
Fresh install fails

### ISSUE THREAD

**Issue by gellenburg** [LemmyNet/lemmy-ansible#38]
Hi guys! Trying to get Lemmy installed on a fresh VPS (Debian 11) and receiving the following error when attempting to go to the site:

`404: FetchError: request to http://lemmy:8536/api/v3/site? failed, reason: connect ECONNREFUSED 172.18.0.2:8536`

Here's the results of the ansible playbook:

```
gme@DESKTOP-R7ILMJV:~/lemmy-ansible$ ansible-playbook -i inventory/hosts lemmy.yml

PLAY [all] *************************************************************************************************************

TASK [check lemmy_base_dir] ********************************************************************************************
skipping: [root@liewrap05.bofhllc.net]

TASK [install python for Ansible] **************************************************************************************
changed: [root@liewrap05.bofhllc.net]

TASK [setup] ***********************************************************************************************************
ok: [root@liewrap05.bofhllc.net]

TASK [install dependencies] ********************************************************************************************
changed: [root@liewrap05.bofhllc.net]

TASK [request initial letsencrypt certificate] *************************************************************************
changed: [root@liewrap05.bofhllc.net]

TASK [create lemmy folder] *********************************************************************************************
changed: [root@liewrap05.bofhllc.net] => (item={'path': '/opt/lemmy/federated.community/', 'owner': 'root'})
changed: [root@liewrap05.bofhllc.net] => (item={'path': '/opt/lemmy/federated.community/volumes/', 'owner': 'root'})
changed: [root@liewrap05.bofhllc.net] => (item={'path': '/opt/lemmy/federated.community/volumes/pictrs/', 'owner': '991'})

TASK [set_fact] ********************************************************************************************************
ok: [root@liewrap05.bofhllc.net]

TASK [add template files] **********************************************************************************************
changed: [root@liewrap05.bofhllc.net] => (item={'src': 'templates/docker-compose.yml', 'dest': '/opt/lemmy/federated.community/docker-compose.yml', 'mode': '0600'})
changed: [root@liewrap05.bofhllc.net] => (item={'src': 'templates/nginx.conf', 'dest': '/etc/nginx/sites-available/federated.community.conf', 'mode': '0644'})

TASK [gather stats on site enabled config] *****************************************************************************
ok: [root@liewrap05.bofhllc.net]

TASK [remove if regular file (legacy) instead of symlink] **************************************************************
skipping: [root@liewrap05.bofhllc.net]

TASK [enable nginx site] ***********************************************************************************************
changed: [root@liewrap05.bofhllc.net]

TASK [add the config.hjson] ********************************************************************************************
changed: [root@liewrap05.bofhllc.net]

TASK [enable and start docker service] *********************************************************************************
ok: [root@liewrap05.bofhllc.net]

TASK [start docker-compose] ********************************************************************************************
changed: [root@liewrap05.bofhllc.net]

TASK [reload nginx with new config] ************************************************************************************
changed: [root@liewrap05.bofhllc.net]

TASK [certbot renewal cronjob] *****************************************************************************************
changed: [root@liewrap05.bofhllc.net]

PLAY RECAP *************************************************************************************************************
root@liewrap05.bofhllc.net : ok=14   changed=10   unreachable=0    failed=0    skipped=2    rescued=0    ignored=0

gme@DESKTOP-R7ILMJV:~/lemmy-ansible$
```

Here's the contents of `config.hjson`:

```
{
  # for more info about the config, check out the documentation
  # https://join-lemmy.org/docs/en/administration/configuration.html

  database: {
    host: postgres
    password: "REDACTED"
  }
  hostname: "federated.community"
  pictrs_url: "http://pictrs:8080"
  federation: {
    enabled: true
  }
  email: {
    smtp_server: "REDACTED"
    smtp_from_address: "noreply@{{ domain }}"
    tls_type: "starttls"
 smtp_login: "REDACTED"
smtp_password: "REDACTED"
  }
}
```

Any ideas?

**Comment by dessalines** [comment]
Show us the output for `sudo docker-compose logs lemmy`

Are you sure your hostname is correct? You should not have changed what's in curly braces, IE db_password or hostname, those get auto-filled. You might have to uninstall and start from scratch.

**Comment by gellenburg** [comment]
Ok, I did that. (The passwords were mismatched, I sync'd them). Still no luck:

```
root@localhost:/opt/lemmy# find . -iname lemmy.hjson
./federated.community/lemmy.hjson
root@localhost:/opt/lemmy# nano ./federated.community/lemmy.hjson
root@localhost:/opt/lemmy# find . -iname docker-compose.yml
./federated.community/docker-compose.yml
root@localhost:/opt/lemmy# nano ./federated.community/docker-compose.yml
root@localhost:/opt/lemmy# cd federated.community/
root@localhost:/opt/lemmy/federated.community# docker-compose up -d
Recreating federatedcommunity_postgres_1 ... 
federatedcommunity_postfix_1 is up-to-date
Recreating federatedcommunity_postgres_1 ... done
federatedcommunity_lemmy_1 is up-to-date
federatedcommunity_lemmy-ui_1 is up-to-date
root@localhost:/opt/lemmy/federated.community# docker-compose restart
Restarting federatedcommunity_postgres_1 ... done
Restarting federatedcommunity_lemmy-ui_1 ... done
Restarting federatedcommunity_lemmy_1    ... done
Restarting federatedcommunity_pictrs_1   ... done
Restarting federatedcommunity_postfix_1  ... done
root@localhost:/opt/lemmy/federated.community# 

```

This is what the app returns:

`404: FetchError: request to http://lemmy:8536/api/v3/site? failed, reason: connect ECONNREFUSED 172.18.0.2:8536`

**Comment by Nutomic** [comment]
You need to look at `sudo docker-compose logs lemmy` again.

**Comment by gellenburg** [comment]
docker-compose.yml;:

```
root@localhost:/opt/lemmy/federated.community# cat docker-compose.yml 
version: '2'

services:
  lemmy:
    image: dessalines/lemmy:0.16.3
    ports:
      - "127.0.0.1:22441:8536"
    restart: always
    environment:
      - RUST_LOG="warn,lemmy_server=info,lemmy_api=info,lemmy_api_common=info,lemmy_api_crud=info,lemmy_apub=info,lemmy_db_queries=info,lemmy_db_schema=info,lemmy_db_views=info,lemmy_db_views_actor=info,lemmy_db_views_moderator=info,lemmy_routes=info,lemmy_utils=info,lemmy_websocket=info"
    volumes:
      - ./lemmy.hjson:/config/config.hjson
    depends_on:
      - postgres
      - pictrs

  lemmy-ui:
    image: dessalines/lemmy-ui:0.16.3
    ports:
      - "127.0.0.1:6472:1234"
    restart: always
    environment:
      - LEMMY_INTERNAL_HOST=lemmy:8536
      - LEMMY_EXTERNAL_HOST=federated.community
      - LEMMY_HTTPS=true
    volumes:
      - ./volumes/lemmy-ui/extra_themes:/app/extra_themes
    depends_on: 
      - lemmy

  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=liewrap05
      - POSTGRES_DB=lemmy
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    restart: always

  pictrs:
    image: asonix/pictrs:0.3.1
    user: 991:991
    ports:
      - "127.0.0.1:29790:8080"
    volumes:
      - ./volumes/pictrs:/mnt
    restart: always
    mem_limit: 200m

  postfix:
    image: mwader/postfix-relay
    environment:
      - POSTFIX_myhostname=federated.community
    restart: "always"
root@localhost:/opt/lemmy/federated.community# 
```

lemmy.hjson:

```
root@localhost:/opt/lemmy/federated.community# cat lemmy.hjson 
{
  # for more info about the config, check out the documentation
  # https://join-lemmy.org/docs/en/administration/configuration.html

  database: {
    host: postgres
    password: "liewrap05"
  }
  hostname: "federated.community"
  pictrs_url: "http://pictrs:8080"
  federation: {
    enabled: true
  }
  email: {
    smtp_server: "REDACTED:587"
    smtp_from_address: "noreply@federated.community"
    tls_type: "starttls"
 smtp_login: "REDACTED"
smtp_password: "REDACTED"
  }
}
```

**Comment by gellenburg** [comment]
docker-compose.yml;:

```
root@localhost:/opt/lemmy/federated.community# cat docker-compose.yml 
version: '2'

services:
  lemmy:
    image: dessalines/lemmy:0.16.3
    ports:
      - "127.0.0.1:22441:8536"
    restart: always
    environment:
      - RUST_LOG="warn,lemmy_server=info,lemmy_api=info,lemmy_api_common=info,lemmy_api_crud=info,lemmy_apub=info,lemmy_db_queries=info,lemmy_db_schema=info,lemmy_db_views=info,lemmy_db_views_actor=info,lemmy_db_views_moderator=info,lemmy_routes=info,lemmy_utils=info,lemmy_websocket=info"
    volumes:
      - ./lemmy.hjson:/config/config.hjson
    depends_on:
      - postgres
      - pictrs

  lemmy-ui:
    image: dessalines/lemmy-ui:0.16.3
    ports:
      - "127.0.0.1:6472:1234"
    restart: always
    environment:
      - LEMMY_INTERNAL_HOST=lemmy:8536
      - LEMMY_EXTERNAL_HOST=federated.community
      - LEMMY_HTTPS=true
    volumes:
      - ./volumes/lemmy-ui/extra_themes:/app/extra_themes
    depends_on: 
      - lemmy

  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=liewrap05
      - POSTGRES_DB=lemmy
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    restart: always

  pictrs:
    image: asonix/pictrs:0.3.1
    user: 991:991
    ports:
      - "127.0.0.1:29790:8080"
    volumes:
      - ./volumes/pictrs:/mnt
    restart: always
    mem_limit: 200m

  postfix:
    image: mwader/postfix-relay
    environment:
      - POSTFIX_myhostname=federated.community
    restart: "always"
root@localhost:/opt/lemmy/federated.community# 
```

lemmy.hjson:

```
root@localhost:/opt/lemmy/federated.community# cat lemmy.hjson 
{
  # for more info about the config, check out the documentation
  # https://join-lemmy.org/docs/en/administration/configuration.html

  database: {
    host: postgres
    password: "liewrap05"
  }
  hostname: "federated.community"
  pictrs_url: "http://pictrs:8080"
  federation: {
    enabled: true
  }
  email: {
    smtp_server: "linycmx01.bofhllc.net:587"
    smtp_from_address: "noreply@federated.community"
    tls_type: "starttls"
 smtp_login: "liewrap05@bofhllc.net"
smtp_password: "R"
  }
}
```
