### ISSUE TITLE
ECONNEREFUSED error

### ISSUE THREAD

**Issue by NIXOYE** [LemmyNet/lemmy-ansible#56]
I uninstalled and installed lemmy from scratch copying the ansible instructions exactly but still get this error `404: FetchError: request to http://lemmy:8536/api/v3/site? failed, reason: connect ECONNREFUSED`

docker-compose.yml:
```
version: '2'

services:
  lemmy:
    image: dessalines/lemmy:0.16.7
    ports:
      - "127.0.0.1:26430:8536"
    restart: always
    environment:
      - RUST_LOG="warn,lemmy_server=info,lemmy_api=info,lemmy_api_common=info,lemmy_api_crud=info,lemmy_apub=info,lemmy_db_queries=info,lemmy_db_schema=info,lemmy_db_views=info,lemmy_db_views_actor=info,lemmy_db_views_moderator=info,lemmy_routes=info,lemmy_utils=info,lemmy_websocket=info"
    volumes:
      - ./lemmy.hjson:/config/config.hjson
    depends_on:
      - postgres
      - pictrs

  lemmy-ui:
    image: dessalines/lemmy-ui:0.16.7
    ports:
      - "127.0.0.1:24415:1234"
    restart: always
    environment:
      - LEMMY_INTERNAL_HOST=lemmy:8536
      - LEMMY_EXTERNAL_HOST=(redacted)
      - LEMMY_HTTPS=true
    volumes:
      - ./volumes/lemmy-ui/extra_themes:/app/extra_themes
    depends_on:
      - lemmy

  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=(redacted)
      - POSTGRES_DB=lemmy
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    restart: always

  pictrs:
    image: asonix/pictrs:0.3.1
    user: 991:991
    ports:
      - "127.0.0.1:22450:8080"
    volumes:
      - ./volumes/pictrs:/mnt
    restart: always
    mem_limit: 200m

  postfix:
    image: mwader/postfix-relay
    environment:
      - POSTFIX_myhostname=(redacted)
    restart: "always"
```

lemmy.hjson:

```
{
  # for more info about the config, check out the documentation
  # https://join-lemmy.org/docs/en/administration/configuration.html

  database: {
    host: postgres
    password: "(redacted)"
  }
  hostname: "(redacted)"
  pictrs_url: "http://pictrs:8080"
  federation: {
    enabled: true
  }
  email: {
    smtp_server: "postfix:25"
    smtp_from_address: "noreply@(redacted)"
    tls_type: "none"
  }
}
```
