### ISSUE TITLE
Can't install lemmy with ansible - Playbook issue with docker-compose

### ISSUE THREAD

**Issue by therealmaxmoon** [LemmyNet/lemmy-ansible#57]
I followed the instruction on [this git repo](https://github.com/LemmyNet/lemmy-ansible), but ansible throws an error.

After executing the following command:

`ansible-playbook -i inventory/hosts lemmy.yml`

the following error is shown:

```
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/home/maxmoon/git_repos/lemmy-ansible/lemmy.yml': line 118, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  - name: start docker-compose
    ^ here
```

The task on line **118** only shows the following:

```
  - name: start docker-compose
    docker_compose:
      project_src: '{{lemmy_base_dir}}/{{domain}}'
      state: present
      pull: yes
      remove_orphans: yes
```

I can't figure out what the problem is, but could it be a problem that I use keys for ssh (instead of passwords) and don't use the default ssh port?

Thank you for your help in advance.
